project_id = "ecdshvqxvjbeizdivpuz"

[functions.ai-agent-reply]
verify_jwt = false

[functions.validate-channel]
verify_jwt = false

[functions.ai-generate-content]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.summarize-meeting]
verify_jwt = false

[functions.personalize-business]
verify_jwt = false
